### PR TITLE
Ub when plugin fail during serve

### LINKED ISSUE #254: Bors for automated CI checks
- Turn off CI checks on all events [push, pull]
- Integrate BORS
- URL https://bors.tech/

### LINKED ISSUE #264: [BUG] Ephemeral plugin prevents the RR process to exit
From the discord: When the app tries to listen already bound 2112 port, it just freezes w/o notifications or errors to end-user.

### PR DESCRIPTION
**Pull request by 48d90782**
1. Remove macOS from GitHub workflow as not properly tested in GitHub (randomly fails)
2. A temporary workaround for the #264 
3. fixes #264 
4. resolves #254

### CODE REVIEW

**Comment by 48d90782** [comment]
bors ping

**Comment by 48d90782** [comment]
bors try

File: service/container_test.go [hunk 1]
```diff
@@ -302,19 +302,22 @@ func TestContainer_ConfigureTwice(t *testing.T) {
...
-	svc := &testService{ok: true}
-
-	c := NewContainer(logger)
-	c.Register("test", svc)
-	assert.Equal(t, 0, len(hook.Entries))
-
-	assert.NoError(t, c.Serve())
-	c.Stop()
-}
+//func TestContainer_ServeEmptyContainer(t *testing.T) {
```
Comment (wolfy-j) [inline service/container_test.go]: Why is it commented out?
